apiVersion: apps/v1
kind: Deployment
metadata:
 name: the-deployment-dev
 labels:
   deployment: demo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        deployment: demo
    spec:
      containers:
      - name: the-container
        image: nginx
